spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://192.168.43.230/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
env:
  test4
girl:
  name: luoli
  age: 19
